package telemetrydb

var TDB_COUNT_CREATE=`
CREATE TABLE IF NOT EXISTS Counters (
  key         TEXT PRIMARY KEY,
  timestamp   INTEGER,
  value       INTEGER
)
`
var TDB_METRIC_CREATE=`
CREATE TABLE IF NOT EXISTS Metric (
  key         TEXT,
  timestamp   INTEGER,
  value       TEXT
)
`
var TDB_HISTORY_CREATE=`
CREATE TABLE IF NOT EXISTS History (
  key         TEXT,
  timestamp   INTEGER,
  value       TEXT
)
`


var TDB_COUNT_IX1_CREATE=`CREATE INDEX IF NOT EXISTS CNT_IX1  ON Counters (timestamp)`
var TDB_METRIC_IX1_CREATE=`CREATE INDEX IF NOT EXISTS MET_IX1 ON Metric (timestamp)`
var TDB_METRIC_IX2_CREATE=`CREATE UNIQUE INDEX IF NOT EXISTS MET_IX2 ON Metric (key)`
var TDB_HISTORY_IX1_CREATE=`CREATE INDEX IF NOT EXISTS HST_IX1 ON History (timestamp)`
var TDB_HISTORY_IX2_CREATE=`CREATE INDEX IF NOT EXISTS HST_IX2 ON History (key)`

var TDB_CREATE=[]string{TDB_COUNT_CREATE,TDB_HISTORY_CREATE,TDB_METRIC_CREATE}
var TDB_IX_CREATE=[]string{TDB_COUNT_IX1_CREATE,TDB_HISTORY_IX1_CREATE,TDB_HISTORY_IX2_CREATE,TDB_METRIC_IX1_CREATE,TDB_METRIC_IX2_CREATE}
