stdlib = import("stdlib")
fmt = import("fmt")
net = import("net")
log = import("tlog")
dtls = import("net/dtls")
os = import("os")

fmt.Println("Current directory", os.Getwd() )
conn = dtls.Dial("127.0.0.1", 60001, "./examples/certificates/client.pem", "./examples/certificates/client.pub.pem")
if conn != nil {
  conn.Write(stdlib.Bytes("Hello DTLS!"))
  con.Close()
}
log.Trace("We are done here")
