fmt = import("fmt")
time = import("time")
flow = import("stdlib/flow")
errors = import("errors")
rand = import("math/rand")

n = rand.Int() % 10
c = 0

func thefun(ctx)  {
fmt.Println("Here it goes for thefun()", n, c)
	if c == n {
		return n, nil
	} else {
		c += 1
		return 0, errors.New("Again!")
	}
}




res, err = flow.Retry(10, thefun)

if err == nil {
	fmt.Println("function() returned:", res)
} else {
	fmt.Println("flow error", err)
}
