//
// cat README.md on stdin of this TSAk script
// cat README.md| ./bin/darwin/tsak  -stdout  -debug  -name "helloworld" -conf ./config.example/tsak.conf -run ./examples/run/stdlibscript3.script
//
fmt = import("fmt")
script = import("stdlib/script")

size, err = script.Exec("cat README.md").Match("golang").CountLines()
if err == nil {
  fmt.Println("There are",size,"lines read from 'cat README.md' matching 'golang'")
} else {
  fmt.Println("Ouch!", err)
}
